### ISSUE TITLE
Heart rate measurement

### ISSUE THREAD

**Issue by Fakher-Hakim** [Aahung/IntoHeart#27]
I can't get the HRM value !!!

**Comment by aahung** [comment]
You mean you download our source code and connect with Polar H7?

**Comment by Fakher-Hakim** [comment]
no i test it on UA-651BLE !!

**Comment by aahung** [comment]
Then you need to look into the BLE service this weird-name device provides. Set a break point at [Here](https://github.com/Aahung/IntoHeart/blob/master/IntoHeart/app/src/main/java/ee3316/intoheart/BLE/SensorConnectionManager.java#L90) and find what services are there. [Here](https://github.com/Aahung/IntoHeart/blob/master/IntoHeart/app/src/main/java/ee3316/intoheart/BLE/GattAttributes.java) are some GattAttributes examples.
